### ISSUE TITLE
Text object not displayed

### ISSUE THREAD

**Issue by Datoh** [17cupsofcoffee/tetra#180] opened 2020-05-10 22:21 UTC
**Summary:**
When there is two identicals Text objects, only the first one is displayed

**Steps to reproduce:**
create two text objects with the same text

See example: [text.txt](https://github.com/17cupsofcoffee/tetra/files/4606840/text.txt)

**Comment by 17cupsofcoffee** [comment] 2020-05-10 23:49
This (along with #125) is due to the fact Tetra currently uses [glyph-brush](https://github.com/alexheretic/glyph-brush) for rendering. glyph-brush is an excellent library, but it doesn't fit very well with Tetra's API, so the way it's currently integrated is a bit of a hack!

In this case, the issue is occuring because glyph-brush sees you're requesting the same piece of text twice and assumes it doesn't need redrawing. I'm working on a refactor that uses rusttype directly, but that's still a little way off being ready. I'll see if there's a short term fix in the meantime.

One workaround would be to just use a single `Text` for each piece of identical content, and then `graphics::draw` it multiple times. That would only work if you know ahead of time which pieces of text you're going to render, though.

**Comment by 17cupsofcoffee** [comment] 2020-05-11 08:07
Oh, it's also worth mentioning that this issue likely occurs when you *render* two identical pieces of text one after the other, rather than when you *create* them one after the other.

**Comment by 17cupsofcoffee** [comment] 2020-06-08 17:13
The text API has been rewritten from scratch on the 0.4 branch, and that has resolved this issue. 🎉 

I will close this when that version is released, but feel free to have a play around with that branch - any feedback on the new API would be appreciated!

**Comment by 17cupsofcoffee** [comment] 2020-06-24 13:20
0.4.0 has been released, so this issue should be fixed now!

**Closed as completed by 17cupsofcoffee** 2020-06-24 13:20 UTC
Labels: Type: Bug, Area: Graphics
