### ISSUE TITLE
Black screen when using Mesa drivers (?)

### ISSUE THREAD

**Issue by wahn** [17cupsofcoffee/tetra#14] opened 2018-12-04 10:03 UTC
After installing the `-lSDL2` dependency:

```sh
apt-get install libsdl2-dev
```

I can compile and run the examples (on **Debian**), but they all render black without error messages:

```sh
$ uname -a
Linux purism 4.15.0-2-amd64 #1 SMP Debian 4.15.11-1 (2018-03-20) x86_64 GNU/Linux
$ cargo run --example hello_world
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/hello_world`
OpenGL Device: Mesa DRI Intel(R) Iris 6100 (Broadwell GT3)
OpenGL Driver: 3.0 Mesa 18.1.9
OpenGL Vendor: Intel Open Source Technology Center
Swap Interval: VSync
```

**Comment by wahn** [comment] 2018-12-04 10:19
They do work on another machine (**CentOS**) though:

```sh
> cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core) 
> cargo run --example texture
   Compiling tetra v0.1.2 (/mill3d/users/jan/git/github/tetra)                                                                              
    Finished dev [unoptimized + debuginfo] target(s) in 4.58s                                                                               
     Running `target/debug/examples/texture`
OpenGL Device: Quadro 4000/PCIe/SSE2
OpenGL Driver: 4.6.0 NVIDIA 390.59
OpenGL Vendor: NVIDIA Corporation
Swap Interval: VSync
```

**Comment by 17cupsofcoffee** [comment] 2018-12-04 10:49
Thank you for the report! I'll look into it further this evening - my work laptop has Intel integrated graphics too, so hopefully I'll be able to reproduce the issue on there. Failing that, might need to spin up a Debian VM or something...

**Comment by 17cupsofcoffee** [comment] 2018-12-04 21:16
I wasn't able to replicate on my laptop, but I think I understand why - from the looks of your log output, it looks like your drivers might be using OpenGL 3.0? I've been targeting 3.2, so perhaps I've used an incompatible feature somewhere... I'll try to force it into 3.0 mode on my machine and see if it breaks :)

**Comment by 17cupsofcoffee** [comment] 2018-12-05 09:57
Dang, no luck - I set the context version to 3.0 on my laptop, and it still seems to work fine for me. Perhaps it's something to do with the Mesa drivers?

**Comment by wahn** [comment] 2018-12-05 10:01
Let  me try something on my side and I will report back ...

```sh
# maybe this will help?
apt-get upgrade mesa-common-dev
```

**Comment by wahn** [comment] 2018-12-05 10:40
I upgraded a couple of things (Mesa + Intel Graphics related) but it didn't fix the problem:

```sh
OpenGL Device: Mesa DRI Intel(R) Iris 6100 (Broadwell GT3)
OpenGL Driver: 3.0 Mesa 18.2.5
OpenGL Vendor: Intel Open Source Technology Center
Swap Interval: VSync
```

**Comment by wahn** [comment] 2018-12-05 10:41
Anyway, don't worry, I can work on the CentOS box. Close if you want ...

**Comment by 17cupsofcoffee** [comment] 2018-12-05 10:56
Strange! Thanks for the report, anyway - I'll close it for now, but hopefully I'll get chance to play around on Debian at some point and see if I can replicate.

Hope you have better luck on your CentOS box!

**Comment by 17cupsofcoffee** [comment] 2018-12-14 10:08
I'm re-opening this, as @VictorKoenders seems to be having a similar issue on Ubuntu.

**Comment by VictorKoenders** [comment] 2018-12-14 10:11
```
Ubuntu 18.10
libsdl2-dev: 2.0.8+dfsg1-4ubuntu1
OpenGL Device: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2)
OpenGL Driver: 3.0 Mesa 18.2.2
OpenGL Vendor: Intel Open Source Technology Center
Swap Interval: VSync
```
Also doesn't seem to work with sdl2's `bundled` feature. I fear it's an openGL issue.

**Comment by 17cupsofcoffee** [comment] 2018-12-14 14:14
@VictorKoenders My suspicion is that the issue might be due to me using `#version 330` stuff in my GLSL - could you try running the examples on the `simplified-glsl` branch that I've just pushed?

**Comment by VictorKoenders** [comment] 2018-12-14 17:10
That seemed to fix it for me!
![screenshot from 2018-12-14 18-09-57](https://user-images.githubusercontent.com/2743142/50017139-97801e00-ffcb-11e8-96a6-22f9be6a1c2d.png)

**Comment by VictorKoenders** [comment] 2018-12-14 17:20
A friend found this resource:  https://stackoverflow.com/a/21567167

```
What they do not tell you, but indirectly imply ("Some drivers don't support all the features required in 
OpenGL 3.3."), is that in the last official release of Mesa (10.0), GL 3.3 only works on Intel hardware. This
 is one of the joys of Intel's close involvement with the Mesa project. If you want reliable GL 3.3 support
 in any form on AMD hardware, you should use fglrx (the proprietary AMD driver) for the time being.
```

**Comment by 17cupsofcoffee** [comment] 2018-12-14 18:22
Ah, the joys of OpenGL...

Anyway, the shader changes don't add any extra complexity/lose us any functionality, so I've merged them into master :)

**Closed as completed by 17cupsofcoffee** 2018-12-14 18:22 UTC
Labels: Type: Bug, Area: Graphics
